name: ReportUI
author: Taylcd
website: https://github.com/Taylcd/ReportUI

version: 1.3.1
api:
  - 3.0.0
  - 4.0.0

main: Taylcd\ReportUI\ReportUI
depend: "FormAPI"

commands:
  report:
    description: Report a player
    permission: report.use
  reportadmin:
    description: Open Report Panel
    permission: report.admin

permissions:
  report.use:
    default: true
  report.admin:
    default: op
  report.admin.notification:
    default: op
